global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  map_type: costmap
  update_frequency: 10.0
  publish_frequency: 10.0
  width: 50
  height: 50
  static_map: false
  rolling_window: false
  transform_tolerance: 0.2 #500
  resolution: 0.05
  
  plugins:
   - {name: static_layer,       type: "costmap_2d::StaticLayer"}
   - {name: wall_layer, type: "costmap_2d::ObstacleLayer"}

  static_layer:
    unknown_cost_value: 0

  wall_layer:
    observation_sources: fake_scan
    fake_scan: {data_type: LaserScan, sensor_frame: map, clearing: true, marking: true, topic: /faked_wall}

